// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptkxnbdsajblrkwdbqof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0a3huYmRzYWpibHJrd2RicW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1OTgxMDcsImV4cCI6MjA3MjE3NDEwN30.p-6SNB8tn8aS91iiuxjuD_k4BpuUrImbQKaDk1jTVHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});